// Google Auth Constants 
export const GOOGLE_SESSION_SECRET = 'GOOGLE_SESSION_SECRET';
export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL';